Traceback (most recent call last):
  File "C:\Users\endyzan\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\endyzan\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1265, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\endyzan\AppData\Roaming\Python\Python311\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\endyzan\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\endyzan\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 703, in async_execute
    await self.async_execute_cell(
  File "C:\Users\endyzan\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1021, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\endyzan\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 915, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import psycopg2
import pandas as pd

# Informasi koneksi ke database PostgreSQL di cloud Aiven
hostname = 'pg-3e119ea2-andi176.a.aivencloud.com'
port = 14814
username = 'avnadmin'
password = 'AVNS_8X2P-_6dzJylk3YECuH'
database = 'defaultdb'

# Membuat koneksi ke database PostgreSQL
conn = psycopg2.connect(
    host=hostname,
    port=port,
    user=username,
    password=password,
    database=database
)

# Membaca data dari database menggunakan Pandas
query = "SELECT * FROM iris"
dataset = pd.read_sql(query, conn)

# tutup koneksi
conn.close()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpsycopg2[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m      4[0m [38;5;66;03m# Informasi koneksi ke database PostgreSQL di cloud Aiven[39;00m

[1;31mModuleNotFoundError[0m: No module named 'psycopg2'
ModuleNotFoundError: No module named 'psycopg2'

